Inverse condition for exit code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -97,14 +97,18 @@ jobs:
 
       - run:
           name: ZAP baseline test of application
-          # Only fail on error code 1, which indicates at least one FAIL was found.
-          # error codes 2 indicate WARN, and should not break the run
+          # It will exit with codes of:
+          # 0: Success
+          # 1: At least 1 FAIL
+          # 2: At least one WARN and no FAILs
+          # 3: Any other failure
+          # Link to above:https://github.com/zaproxy/zaproxy/blob/main/docker/zap-baseline.py#L31-L35
           command: |
               (
                 docker run -t owasp/zap2docker-stable zap-baseline.py \
                 -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/zap-baseline.conf \
                 -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):3000 || \
-                if [[ $? -ne 1 && $? -ne 3 ]]; then exit 0; else exit 1; fi;
+                if [[ $? -e 0 || $? -e 2 ]]; then exit 0; else exit 1; fi;
               )
 
   build-deploy-staging:
